version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - weather-service
      - log-service

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"

  weather-service:
    build: ./weather-service
    ports:
      - "3002:3002"
    environment:
      # Imposta qui la tua API key per OpenWeatherMap, oppure usala direttamente nel codice
      - OPENWEATHER_API_KEY=your_api_key_here

  log-service:
    build: ./log-service
    ports:
      - "3003:3003"
    environment:
      # Il log service si collega a Elasticsearch tramite questo hostname (definito nel docker-compose)
      - ELASTICSEARCH_HOST=http://elasticsearch:9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata: