name: CI Pipeline Backend

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ "api-gateway", "user-service", "weather-service", "log-service" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Debug: Mostra la directory corrente e l'elenco dei file nella radice del repository
      - name: Debug: List repository root
        run: |
          echo "Current directory: $(pwd)"
          ls -la ${{ github.workspace }}

      # Debug: Elenca il contenuto della cartella backend
      - name: Debug: List backend directory
        run: |
          echo "Listing contents of 'backend':"
          ls -la ${{ github.workspace }}/backend

      # Debug: Elenca i file della cartella del microservizio corrente
      - name: Debug: List files in backend/${{ matrix.service }}
        run: |
          echo "Listing files in backend/${{ matrix.service }}:"
          ls -la ${{ github.workspace }}/backend/${{ matrix.service }}

      # Install dependencies per il microservizio corrente
      - name: Install dependencies for ${{ matrix.service }}
        working-directory: ${{ github.workspace }}/backend/${{ matrix.service }}
        run: |
          echo "Changing directory to: $(pwd)"
          ls -la
          npm install

      # Esegue la build se è definito lo script "build"
      - name: Build project for ${{ matrix.service }}
        working-directory: ${{ github.workspace }}/backend/${{ matrix.service }}
        run: |
          echo "Changing directory to: $(pwd)"
          if npm run | grep -q "build"; then
            npm run build
          else
            echo "No build script defined for ${{ matrix.service }}; skipping build step."
          fi