name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ "api-gateway", "log-service", "user-service", "weather-service" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Passo di debug per controllare la struttura del repository (opzionale)
      - name: Debug: List repository root
        run: |
          echo "Repository structure:"
          ls -la

      - name: Debug: List contents of 48h-weather-app/backend
        run: |
          echo "Contents of 48h-weather-app/backend:"
          ls -la 48h-weather-app/backend

      # Esegue npm install in ciascuna cartella specifica
      - name: Install dependencies for ${{ matrix.service }}
        run: |
          echo "Changing directory to 48h-weather-app/backend/${{ matrix.service }}"
          cd 48h-weather-app/backend/${{ matrix.service }} && \
          echo "Current directory: $(pwd)" && \
          ls -la && \
          npm install