name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ "api-gateway", "user-service", "weather-service", "log-service" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Step di debug per verificare la struttura
      - name: List files in repository root
        run: ls -la

      - name: Install dependencies for api-gateway
        working-directory: ./backend/api-gateway
        run: npm install

      - name: Build project for ${{ matrix.service }}
        working-directory: ./backend/${{ matrix.service }}
        run: |
          if npm run | grep -q "build"; then
            npm run build
          else
            echo "No build script defined for ${{ matrix.service }}; skipping build step."
          fi