name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ "api-gateway", "user-service", "weather-service", "log-service" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Debug: Visualizza i file nella radice per confermare la struttura
      - name: List repository root
        run: ls -la

      # Debug: Visualizza i file nella cartella del microservizio
      - name: List files in backend/${{ matrix.service }}
        run: ls -la backend/${{ matrix.service }}

      - name: Install dependencies for ${{ matrix.service }}
        working-directory: backend/${{ matrix.service }}
        run: npm install

      - name: Build project for ${{ matrix.service }}
        working-directory: backend/${{ matrix.service }}
        run: |
          if npm run | grep -q "build"; then
            npm run build
          else
            echo "No build script defined for ${{ matrix.service }}; skipping build step."
          fi